Handle orphaned events at the end of the match
team3663/Scouting-App pull request #295
Opened 2024-10-21 23:53 UTC by Jeff-Stammler

Fixes #237

2024-10-25 23:37 UTC, AdrielStammler requested changes

2024-10-25 23:37 UTC, AdrielStammler commented on app/src/main/java/com/team3663/scouting_app/activities/Match.java
> +                            dialog.dismiss();
What is the purpose of this line? What functionally does it do?

2024-10-25 23:37 UTC, AdrielStammler commented on app/src/main/java/com/team3663/scouting_app/activities/Match.java
> +                                        dialog.dismiss();
Ditto

2024-10-26 02:02 UTC, EllaNorby approved these changes

2024-10-26 02:07 UTC, AdrielStammler approved these changes

2024-10-26 02:08 UTC, merged